### ISSUE TITLE
文章出处问题

### ISSUE THREAD

**Issue by wzdnzd** [shunliz/Machine-Learning#2]
首先，很感谢作者分类整理，然后，很大一部分内容来自[博客园-刘建平Pinard](https://www.cnblogs.com/pinard)，是不是注明出处会更好？

**Comment by zhanlaoban** [comment]
楼主就这么拿刘建平的博文内容来赚取打赏？？？

**Comment by shunliz** [comment]
@wzdnzd，内容都是从网上搜集整理的。是有一部分是来自刘建平的博客。懒得一个一个注明。

**Comment by shunliz** [comment]
@zhanlaoban 拿刘建平的博文内容来赚打赏？我拿我在网上搜集整理的内容赚打赏，不会说话就回去让你家人再教教，回炉一下。你小学语文老师都替你汗颜。
赚不赚打赏是我的事情，说好听一点。你也赚一个试试。拿老外内容的我看也没见有几个人关注。
不好听，关你屁事。有本事你把老外的内容也搞上去，说不定我会打赏你。

**Comment by zhanlaoban** [comment]
唉。素质堪忧。

**Comment by shunliz** [comment]
智力型语言障碍，你就不要乱喷了。‘’赚取打赏”， 隔着屏幕都能闻到你的酸臭味。

**Comment by zhanlaoban** [comment]
唉。你真的有理就别删我评论。算了算了，请你把我的评论都删了，科研去了。

**Comment by shunliz** [comment]
书读傻了吧你
